### ISSUE TITLE
build.sh 실행시 no rule to make target error (해결)

### ISSUE THREAD

**Issue by BettyKwon** [ossnu/osfall2016#10]
안녕하세요.
build.sh를 실행했을 때 no rule to make target 에러가 뜨는데요... 
어떻게 해결해야할지 몰라서 질문드려요

첫 번째 스크린 샷(제일 아래 make 에러를 봐주세요)은 에러메시지이고, 두 번째 스크린샷은 환경변수 설정값과 툴체인 위치입니다.
혹시 비슷한 경험을 했다가 해결하신 분 계신가요?

![screen shot 2016-10-01 at 1 41 35 pm](https://cloud.githubusercontent.com/assets/4114543/19011818/6a0aba88-87dd-11e6-9fe2-8b8f261fa3d6.png)

![screen shot 2016-10-01 at 2 04 34 pm](https://cloud.githubusercontent.com/assets/4114543/19011922/20580726-87e0-11e6-9038-209e421d097e.png)

**Comment by BettyKwon** [comment]
해결했네요.
같은 문제 있으신 분들은 make distclean 후 해보세요!
빌드하는데 한시간 정도 걸렸네요

**Comment by Ailrun** [comment]
해결된 경우에는 제목을 바꾸시기보다 이슈를 Close하시는게 더 좋습니다
