### ISSUE TITLE
build.sh 중 file format not recognized

### ISSUE THREAD

**Issue by Rajin9601** [ossnu/osfall2016#11]
![2016-10-01 7 40 27](https://cloud.githubusercontent.com/assets/7630229/19013565/496ed232-880f-11e6-9344-1897ad044ec1.png)

상황 설명: 팀 git 레포에서 커널 코드를 받은 후, 빌드를 하였다.
그리고 나서 git pull을 한 후 에 빌드를 하니 저 에러가 뜨면서 빌드가 더이상 진행되지가 않습니다.
레포에 올라간 코드는 팀원 컴퓨터에서 빌드가 되는 것을 확인했습니다.

**Comment by wonook** [comment]
제가 어제 해결해줬습니다
