### ISSUE TITLE
다운로드 모드의 타이젠이 ubuntu에 인식되지 않습니다

### ISSUE THREAD

**Issue by Dongjoo-Kim** [ossnu/osfall2016#13]
사진으로 확인할 수 있듯이 다운로드 모드가 아닌 경우 정상적으로 인식이 되고 sdb로도 확인이 가능하였는데 다운로드 모드로 연결을 하면 인식이 불가능하네요. 혹시 몰라 다른 컴퓨터에서도 진행하였으나 같은 상황입니다. 혹시 이런 문제가 발생하였거나 해결책을 아시는 분 없으신가요? 

![20161001_211442](https://cloud.githubusercontent.com/assets/14817269/19014065/0625303e-881e-11e6-8143-554d12b3c899.jpg)

![20161001_211521](https://cloud.githubusercontent.com/assets/14817269/19014046/cfd4dbf6-881d-11e6-987b-e24787ef0fb0.jpg)

**Comment by BettyKwon** [comment]
저도 같은 문제를 겪고 있어요ㅠ

**Comment by pjbear1215** [comment]
closed된 issue중에 비슷한 문제가 있었던 것 같은데 
VirtualBox에서 USB를 download mode에서만 잡아두고 일반부팅에서는 안잡아놔서 생겼던 문제라고 합니다. mode에 따라서 USB 설정을 새로 virtualbox에서 해줘야 하는게 아닌가 싶네요

**Comment by Dongjoo-Kim** [comment]
버츄얼박스가 아니라 멀티부팅한 우분투에서 발생한 상황입니다. 멀티부팅한 경우에서도 다른 작업이 필요한 건가요?

**Comment by pjbear1215** [comment]
download 모드에서 원래 sdb devices 명령어가 먹혔는지 기억이 잘 안나는데 lthor 명령어를 통한 플래싱 작업이 불가능한건가요?

**Comment by Dongjoo-Kim** [comment]
![2016-10-03 01 02 40](https://cloud.githubusercontent.com/assets/14817269/19021842/2da29b3c-8905-11e6-95a5-6b3e6640d1dc.png)
![2016-10-03 01 05 00](https://cloud.githubusercontent.com/assets/14817269/19021861/77450298-8905-11e6-91cf-f207f497a34b.png)

다운로드 모드의 경우 위와 같이 USB port를 찾지 못하였다고 합니다. 다운로드 모드가 아닐 경우에는 아래처럼 에러메세지를 출력합니다.

**Comment by Dongjoo-Kim** [comment]
우분투를 12.04에서 14.04로 업그레이드하니 해결되었습니다. 12.04 버전을 사용하지 않는 것이 좋아보이네요.
