### ISSUE TITLE
sdb 관련 링크

### ISSUE THREAD

**Issue by mori-inj** [ossnu/osfall2016#2]
타이젠 세팅 부분의 x. Copy the file to/from the device 항목의 sdb관련 링크로 들어가도 sdb와 관련된 내용을 바로 볼 수 없는것 같습니다. 
https://developer.tizen.org/development/tools/common-tools/smart-development-bridge

**Comment by pjbear1215** [comment]
관련 부분 수정하였습니다. 감사합니다.
