### ISSUE TITLE
ptree DFS에서 child의 순서 문의

### ISSUE THREAD

**Issue by minsuu** [ossnu/osfall2016#25]
과제 description에 적힌 것을 보면, `depth-first-search (DFS) pre-ordering order`라 되어있는데,
제가 알기로는 DFS pre-order가 child의 순회 순서까지를 말해주지는 않는데요.
그렇다면 리턴되는 tree information에서의 child의 순회 순서는 따로 정해지지 않은 게 맞나요?
(younger->older, 혹은 older->younger의 순서를 말씀드리는 것입니다.)

**Comment by pjbear1215** [comment]
제가 기억하는게 맞다면 최상위 root가 oldest라면 pre-order일 경우, child의 순회순서는 older->younger 입니다.

**Comment by minsuu** [comment]
답변 감사합니다~
