### ISSUE TITLE
checkpatch.pl 파일 문제

### ISSUE THREAD

**Issue by BettyKwon** [ossnu/osfall2016#26]
checkpatch.pl은 프로젝트에 원래 들어가있던 걸로 돌리나요, 
아니면 https://github.com/torvalds/linux/blob/master/scripts/checkpatch.pl에 올라온 것으로 돌리나요?

**Comment by pjbear1215** [comment]
프로젝트에 포함되어있는걸로 돌리시면 될 것 같습니다.
