### ISSUE TITLE
타이젠은 32비트인가요 64비트인가요?

### ISSUE THREAD

**Issue by mori-inj** [ossnu/osfall2016#3]
시스템콜 구현할때 32빗 모드 기준으로 작성해야 하나요? 64빗 모드로 작성해야하나요?
arch/ 디렉토리 아래에도 arm이 있고 arm64가 있던데 툴 체인을 32빗을 사용하니 32빗 모드라 생각하면 되는건가요??

**Comment by pjbear1215** [comment]
아마 32비트로 작성하시면 될 것 같은데, 확답은 못드리겠고, 해보시면 쉽게 알 수 있을 것 같습니다. 감사합니다.
