### ISSUE TITLE
Questions about 'trial's prime factorization

### ISSUE THREAD

**Issue by luwalong** [ossnu/osfall2016#31]
Do we have maximum number of file `integer`? What should we print for the result: mere prime factors' list or '2^3*3^1' form?

**Comment by pjbear1215** [comment]
As far as I known, it takes quite long time to calculate the prime factor of the number as the number is bigger. So you don't have to worry about that if you simply start the programs with a small number, growing the number.

The format of the result is not that important. We'd just like to know whether the result is accurate or not.
