### ISSUE TITLE
프로젝트 채점 결과

### ISSUE THREAD

**Issue by mori-inj** [ossnu/osfall2016#35]
지금까지 제출한 프로젝트1과 2의 채점 결과를 언제즘 알 수 있을까요??
충족해야할 채점 기준 등에 대해서도 추가로 알고 싶습니다.

**Comment by voidbag** [comment]
채점은 종강전에, 공지할 것이고
요청하시면, 감점이유를 말씀드리도록 하겠습니다.

감사합니다.

**Comment by mori-inj** [comment]
이전 프로젝트들에 대한 감점 요소를 알아야 그 다음 프로젝트에서 이를 반영해 개선할 수 있을 것 같습니다. 
감점당할 수 있는 요소나 학생들이 공통적으로 하기 쉬운 실수 등등 주의해야 할 것들에 대한 명시가 없으면 추후에 동일한 이유로 감점이 되었을때 수정을 못하여 피할 수 있는 감점을 받을 수 있다고 생각합니다

**Comment by voidbag** [comment]
명시된 기능 모두 구현하고, documention을 성실히 작성하면, 만점입니다.

Requirement에 따라서 성실히 과제를 수행하시면 될 것 같습니다.

감사합니다.
