### ISSUE TITLE
cpu hotplug

### ISSUE THREAD

**Issue by BettyKwon** [ossnu/osfall2016#37]
멀티코어 환경에서 코드를 테스트하려는데
자동으로 cpu0을 제외한 모든 cpu들이 shutdown되어서 테스트하기가 힘듭니다.
구글링을 꽤 해봤는데 타이젠에서 강제로 셋업해놓은 것인지... 여러 방법을 사용해봤는데도명령어나 변수 설정으로 cpu를 모두 사용할 수 있게 설정하는데 실패했습니다.
멀티코어 환경에서 테스트해볼 수 있도록 cpu를 모두 깨워놓는 방법을 알려주실 수 있을까요?

**Comment by pjbear1215** [comment]
기본적으로 모든 CPU들이 필요할땐 전부 깨어나있지 않나요? 제가 예전에 했을땐 그런 경우는 없었던 것 같은데 혹시 다른 조에서도 비슷한 증상이 있는지 궁금합니다.
수정하지 않은 커널에서 정말 CPU0밖에 활성화가 안되는지 확인해보시기 바랍니다.

**Comment by BettyKwon** [comment]
확인했습니다. 충분한 태스크가 주어지지 않을 때 이런 경우가 발생하는 것 같습니다.
