### ISSUE TITLE
프로젝트 4 기한에 대한 문의

### ISSUE THREAD

**Issue by shuuki4** [ossnu/osfall2016#39]
지난주쯤 수업시간에 교수님께서 시험을 19일에 본다면 프로젝트 듀를 21일까지 늘려주겠다는 말씀을 하셨고 실제로 그 이후로 시험을 19일에 보는 것으로 일정이 결정났는데요,
README에 적혀있는 프로젝트 4의 제출 기한은 12월 19일까지네요.
프로젝트 4의 듀에 대해 정확하게 공지해주실 수 있나요?

**Comment by Ailrun** [comment]
변경되었네요
