### ISSUE TITLE
gpsupdate 프로그램에 대한 문의

### ISSUE THREAD

**Issue by Ailrun** [ossnu/osfall2016#40]
gpsupdate 를 user space program 으로 작성하라고 하셨는데,
Tizen API 를 사용해서 현 위치를 받아와 기록하는 프로그램을 만들라는 말씀이신가요?

구체적으로 gpsupdate 가 하는 역할이 무엇이며
개발할 때 어느 범위까지 사용이 가능한지 여쭙고 싶습니다.

**Comment by pjbear1215** [comment]
Tizen API를 따로 사용할 필요는 없고, 
임의의 위치로 일정시간마다 변경해주는식으로 시뮬레이션 해주시면 됩니다.
아래부분을 참조하시면 됩니다.
For testing you can create an array of gps_location structs that include predefined gps values and simply round robin through the array every x seconds to test in the device.

**Comment by Ailrun** [comment]
> For example, if a file is created or modified lastly at Bldg. 301, it should not be allowed to be opened when your user program opens the file at Bldg. 302.

이런 것도 시뮬레이션으로 처리한다고 이해하면 되나요?
구체적이고 접근 가능한 장소가 나와있어서 실제 기기의 위치를 읽어야 하는 것으로 이해했었습니다.

**Comment by pjbear1215** [comment]
네 301동 302동은 단순 예시로서, 위치는 그냥 가상의 위치로 처리하시면 됩니다.
해당 프로그램은 단순히 테스트를 위한 프로그램 작성이므로 복잡하게 구현하실 필요는 없습니다.
임의의 한 장소에서 생성되거나 수정된 파일이 임의의 다른 장소에서 열리지 않으면 됩니다.
