### ISSUE TITLE
mkmodimg.sh 실행 중 에러

### ISSUE THREAD

**Issue by luwalong** [ossnu/osfall2016#5]
CROSS_COMPILE까지 export를 마친 상태인데 다음과 같은 에러를 뱉으며 실행이 비정상적으로 종료됩니다;

```
luwalong@lVB:~/linux-3.10-sc7730$ sudo scripts/mkmodimg.sh
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
make[1]: `include/generated/mach-types.h' is up to date.
  CC      kernel/bounds.s
gcc: error: unrecognized argument in option ‘-mabi=aapcs-linux’
gcc: note: valid arguments to ‘-mabi=’ are: ms sysv
gcc: error: unrecognized command line option ‘-mlittle-endian’
gcc: error: unrecognized command line option ‘-mno-thumb-interwork’
make[1]: *** [kernel/bounds.s] Error 1
make: *** [prepare0] Error 2
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
make[1]: `include/generated/mach-types.h' is up to date.
  CC      kernel/bounds.s
gcc: error: unrecognized argument in option ‘-mabi=aapcs-linux’
gcc: note: valid arguments to ‘-mabi=’ are: ms sysv
gcc: error: unrecognized command line option ‘-mlittle-endian’
gcc: error: unrecognized command line option ‘-mno-thumb-interwork’
make[1]: *** [kernel/bounds.s] Error 1
make: *** [prepare0] Error 2
Failed to make modules
```

검색을 해보니 arm 컴파일링에 사용되는 옵션인 것 같은데, toolkit을 잘못 다운로드 받은건지, 어떻게 된건지 정확히 모르겠습니다.

build.sh도 원인모를 이유때문에 원인모를 해결책으로 해결됐는데 이건 그마저도 되지 않네요..

instruction을 따라 왔는데, 어디에 원인이 있는지 알려주실 수 있으신가요?

VirtualBox 5.x에서 Ubuntu 14.04 LTS 64bit 사용중입니다

**Comment by pjbear1215** [comment]
컴파일할 때, 크로스 컴파일러 툴체인이 사용되지 않고 일반 x86으로 컴파일을 하려고 해서 발생하는 문제인 것으로 보입니다.
export CROSS_COMPILE="<extraction path>/opt/tizen-toolchain-4.9~git-i686_armv7l-tizen-linux-gnueabi-20151113/bin/armv7l-tizen-linux-gnueabi-"
export가 제대로 되었는지 한번 확인 부탁드립니다.
그리고
$ sudo ls
$ script/mkmodimg.sh
이렇게 컴파일 시도해보시기 바랍니다.

**Comment by luwalong** [comment]
ㅠㅠㅠmkmodimg.sh 실행 중에 sudo를 붙이면 위의 에러가 계속 나고 sudo를 붙이지 않으면 아예 Permission Denied가 어디선가 나옵니다ㅠㅠ

**Comment by pjbear1215** [comment]
sudo ls 를 한번 해주고 나면 permission denied는 발생하지 않을텐데 이상하네요. 참고로  CROSS_COMPILE 부분은 본인의 설치경로에 맞게 설정해주셔야 합니다. 어디선가 꼬인 것 같은데, 아예 차음부터 다시 시작해보시는 것도 방법일 것 같습니다.

**Comment by luwalong** [comment]
헉 sudo "CROSS_COMPILE=$CROSS_COMPILE" scripts/mkmodimg.sh로 하니까 됐습니다!
그런데 이전에도 sudo echo $CROSS_COMPILE하면 잘 나왔었는데 또 원인모를 해결책으로 해결했네요...
