### ISSUE TITLE
Git checkout error

### ISSUE THREAD

**Issue by Ailrun** [ossnu/osfall2016#6]
While checking out git repository of tizen to `tizen_2.4` branch,
following error occurs.

```
error: unable to create file drivers/gpu/drm/nouveau/core/subdev/i2c/aux.c (No such file or directory)
```

Is there any problem with???

**Comment by pjbear1215** [comment]
i haven't seen that kind of errors. after some googling, i found that in windows there is maximum file path length limit and we can't create a file named aux.c. you are doing this project on Ubuntu 12.04/14.04, right?

**Comment by Ailrun** [comment]
Ye I'm on Ubuntu 12.04

**Comment by pjbear1215** [comment]
have you checked the permission of that folder? do you have permission to create a file in the folder?

**Comment by Ailrun** [comment]
I'm the owner and in the owner group of the directory, and permission of directory is even 777(because of error, I change the permission)

**Comment by pjbear1215** [comment]
then, i have no idea... you shoud give me the whole error messages.
but what we need is only the tizen source code to build.
one of your members can help uploading the tizen_2.4 source code to your team repository.
