### ISSUE TITLE
도움될만한(?) 자료

### ISSUE THREAD

**Issue by mori-inj** [ossnu/osfall2016#7]
https://drive.google.com/file/d/0B6MtamZycrn2eWdjM1I3blc2S00/view?usp=sharing
(oracle virtual box ova file입니다. 맥이랑 윈도에서 잘 돌아가는걸 확인했습니다. 
세팅이 되어 있으니 import 하신 후 바로 사용하시면 됩니다. 비밀번호는 asdf1234입니다.
hello world를 출력하는 샘플 시스템콜을 깜빡하고 안 지우고 압축했는데 참고하시기 바랍니다.)
[Linux Kernel Exploration Guide.pdf](https://github.com/ossnu/osfall2016/files/493632/Linux.Kernel.Exploration.Guide.pdf)
(지난학기 os 수업에 쓰인 자료라고 합니다.)

**Comment by mori-inj** [comment]
#!/bin/sh
export PATH="$PATH:/home/mori/Downloads/opt/tizen-toolchain-4.9~git-i686_armv7l-tizen-linux-gnueabi-20151113/bin/"
./build.sh tizen_tm1 USR
sudo ls
export CROSS_COMPILE="/home/mori/Downloads/opt/tizen-toolchain-4.9~git-i686_armv7l-tizen-linux-gnueabi-20151113/bin/armv7l-tizen-linux-gnueabi-"
scripts/mkmodimg.sh
tar cf IMAGE.tar -C arch/arm/boot/ dzImage -C ../../../usr/tmp-mod modules.img

**Comment by minsuu** [comment]
감사합니다. 많은 도움이 될 것 같네요!
