### ISSUE TITLE
sdb사용 시 developer mode 사용문의

### ISSUE THREAD

**Issue by luwalong** [ossnu/osfall2016#8]
sdb 링크를 타고 가서 디바이스를 USB Debugging로 바꾸려고 하는데 아예 Settings에 More System Setting이라는게 없습니다...
설명을 보니 sdb는 download mode에서 실행하는게 아닌 것 같은데 그냥 sdb devices를 해봐도 List에 뜨질 않네요ㅠㅠ 어떻게 해야 하나요?

**Comment by pjbear1215** [comment]
제가 테스트해본 모든 기기들은 굳이 설정을 바꾸지 않아도 정상적으로 인식이 되었습니다. 

조원분들꺼로 한번 테스트해보시고, 본인 폰만 이상이 있으시다면 302동 319-1호로 가져오시면 교체해드리겠습니다. 

말씀하신대로 그냥 노멀부팅으로 부팅한 후에 USB에 연결하고 sdb devices 를 하시면 됩니다.  

아래 명령어를 시도해보시는 것도 좋을 것 같습니다.

```
sdb kill-server
sdb start-server --only-detect-tizen
```

**Comment by luwalong** [comment]
여전히 안됩니다... 조원들 디바이스로 테스트해보고 교체받으러 가보겠습니다ㅠㅠㅠ

**Comment by pjbear1215** [comment]
$ which sdb
를 수행하면, <your path>/tizen-sdk/tools/sdb 라고 나오나요?

**Comment by luwalong** [comment]
해결됐습니다ㅎㅎ... 조원들 컴퓨터들로 해보니까 VirtualBox에서 USB를 download mode에서만 잡아두고 일반부팅에서는 안잡아놨었네요ㅠㅠㅠㅠㅠ 번거롭게해드려 죄송합니다!!
