### ISSUE TITLE
build.sh 실행중 오류입니다.

### ISSUE THREAD

**Issue by ckdrl2723** [ossnu/osfall2016#9]
![20160929_085429](https://cloud.githubusercontent.com/assets/14194365/18938545/3cf60a52-8634-11e6-8585-fc50727ade4e.png)

다음과 같은 문제가 일어나는데 해결방안 부탁드립니다 ㅜㅜ

그리고 혹시 window에서 실행하신분 있나요?

**Comment by pjbear1215** [comment]
PATH에 크로스컴파일러 경로가 제대로 등록되지 않은 것 같습니다.
echo $PATH 를 수행해서 제대로 등록되었는지 한번 확인해보시기 바랍니다.
```
$ export PATH="$PATH:<extraction path>/opt/tizen-toolchain-4.9~git-i686_armv7l-tizen-linux-gnueabi-20151113/bin/"
```
그리고 sudo는 제가 sudo를 사용하라고 명시한 곳에서만 사용해도 상관없습니다.
만약에 permission관련 문제가 발생하면, 그건 해당 경로의 owner가 root로 되어있다든가 하는 문제일 가능성이 높습니다. 
```
$ sudo chown bob:bob 해당폴더 
```
등을 통해서 owner를 수정해주시면 됩니다.
그리고 window에서는 정상적으로 동작하는 것을 장담할 수 없으니 우분투에서 진행해주시기 바랍니다.

**Comment by ckdrl2723** [comment]
답변 감사드립니다~

**Comment by gorgo94** [comment]
똑같은 문제를 겪고 있는데, echo $PATH 수행해서 나온 경로를 그대로 복사 붙여넣기 해서 들어가보면 필요한 gcc 파일이 존재하는데 여전히 build.sh 를 돌려보면 없다고 나오네요.. 혹시 이럴 땐 어떻게 해결하나요

**Comment by BettyKwon** [comment]
@gorgo94 which armv7l~~gcc 를 수행했을 때 나오는 경로도 제대로인가요? 혹시 /가 두개가 들어갔거나하는 문제가 있는지 확인해보세요! 그리고 make distclean도 한 후에 빌드 실행해보세요

**Comment by Ailrun** [comment]
1. `echo $PATH`의 결과값도 올려주시는 편이 원인을 파악하기 좋습니다.
2. `$PATH`에 `~`가 포함되는 경우, `~`를 해당하는 절대경로 (사용자의 Home directory)로 변경해주세요.
